### ISSUE TITLE
add "prefix: " support

### ISSUE THREAD

**Issue by MCdragonmasters** [JohnHeikens/IntelliSkript#53]
idk if u know this but u can change the "skript:< command name >" prefix but i get an error only in vscoode that tells me to make sure my code is in triggers
<img width="888" alt="Screenshot 2024-05-08 at 11 06 53 AM" src="https://github.com/JohnHeikens/IntelliSkript/assets/116000479/fac23a8f-debf-42c0-bfef-5a23df4b1b78">

**Comment by JohnHeikens** [comment]
i am sorry, but i am not actively updating this github repository anymore at the moment. you could fix it yourself and send a pull request, which i will accept. there is a list in the code with things which can be below the keyword "command". simply add "prefix" to that.

**Comment by MCdragonmasters** [comment]
wish i could make a pr but i dont know java.....
