### ISSUE TITLE
add `set <skripttype>:` for custom expressions

### ISSUE THREAD

**Issue by MCdragonmasters** [JohnHeikens/IntelliSkript#74]
![image](https://github.com/JohnHeikens/IntelliSkript/assets/116000479/d1d4139a-1661-423d-bffc-3e8d2edd33ea)

**Comment by JohnHeikens** [comment]
i didn't even know that was a thing and thought the set type was equal to the return type O.o
there will be support for it soon 😊

**Comment by JohnHeikens** [comment]
are you able to have multiple setters for different types?

**Comment by JohnHeikens** [comment]
@MCdragonmasters

**Comment by MCdragonmasters** [comment]
i believe every type u can set a variable to

**Comment by MCdragonmasters** [comment]
> are you able to have multiple setters for different types?

wdym by that?

**Comment by JohnHeikens** [comment]
> > are you able to have multiple setters for different types?
> 
> wdym by that?

for instance:
set string:
    blahblah
set number:
    blahblah

**Comment by MCdragonmasters** [comment]
not sure what u mean by `for instance` but the other 2 are correct

**Comment by JohnHeikens** [comment]
for instance means "for example,". it's not a line of code 😊
thank you!

**Comment by JohnHeikens** [comment]
![image](https://github.com/JohnHeikens/IntelliSkript/assets/50964021/bbca1db2-5340-4964-be67-f7863f77968f)
